!obj:pylearn2.train.Train {
    dataset: &train !obj:pylearn2.datasets.pylearn2_MedleyDB.MedleyDB {
        which_set: 'train',
        path: "/home/jq401/data/patch_data_20_40_splitted.mat"
    },
    model: !obj:pylearn2.models.mlp.MLP {
        batch_size: 30,
        input_space: !obj:pylearn2.space.Conv2DSpace {
            shape: [1, 44100],
            num_channels: 2,
            axes: ['c', 0, 1, 'b'],
        },
        layers: [ !obj:pylearn2.models.mlp.ConvRectifiedLinear {
                     layer_name: 'h0',
                     output_channels: 64,
                     irange: .05,
                     border_mode: 'valid',
                     kernel_shape: [1, 401],
                     pool_shape: [1, 16],
                     pool_stride: [1, 8],
                 }, !obj:pylearn2.models.mlp.ConvRectifiedLinear {
                     layer_name: 'h1',
                     output_channels: 64,
                     irange: .05,
                     kernel_shape: [1, 425],
                     border_mode: 'valid',
                     pool_shape: [1, 12],
                     pool_stride: [1, 6],
                 }, !obj:pylearn2.models.mlp.RectifiedLinear {
                     layer_name: 'h2',
                     irange: .05,
                     dim: 300,
                 }, !obj:pylearn2.models.mlp.Sigmoid {
                     irange: 0.05,
                     max_col_norm: 1.9365,
                     layer_name: 'y',
                     dim: 82
                 }
                ],
    },
    algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
        set_batch_size: True,
        batch_size: 30,
        learning_rate: .04,
        learning_rule: !obj:pylearn2.training_algorithms.learning_rule.Momentum {
            init_momentum: 0.5,
        },
        train_iteration_mode: 'even_shuffled_sequential',
        monitor_iteration_mode: 'even_sequential',
        monitoring_dataset: {
            'test':!obj:pylearn2.datasets.pylearn2_MedleyDB.MedleyDB {
                  which_set: 'test',
                  path: "/home/jq401/data/patch_data_20_40_splitted.mat"
             }
        },
        cost: !obj:pylearn2.costs.mlp.dropout.Dropout {
               input_include_probs: { 'h2': .5 },
        },
        termination_criterion: !obj:pylearn2.termination_criteria.And {
            criteria: [
                !obj:pylearn2.termination_criteria.MonitorBased {
                    channel_name: "test_y_01_loss",
                    prop_decrease: 0.,
                    N: 10
                },
                !obj:pylearn2.termination_criteria.EpochCounter {
                    max_epochs: 500
                },
            ]
        },
    },
    extensions:
        [ !obj:pylearn2.train_extensions.best_params.MonitorBasedSaveBest {
             channel_name: 'test_y_01_loss',
             save_path: "MedleyDB_best.pkl",
        }, !obj:pylearn2.training_algorithms.learning_rule.MomentumAdjustor {
            start: 1,
            saturate: 20,
            final_momentum: .95
        }
    ]
}